#' Filter NCRN datasets to active characteristics and sites
#'
#' @description
#' Creates and/or reads "active-only" CSVs for both **metadata** and **data**
#' to stabilize downstream analyses and Shiny apps by excluding retired sites
#' and inactive characteristics. When the active-only files do not yet exist,
#' they are generated by filtering the provided base CSVs; otherwise, the
#' existing active-only metadata is reused to ensure consistent filtering of the data.
#'
#' @param Network Character scalar. A network identifier used to construct file
#'   paths under `Data/<Network>/`.
#' @param metadataname Character scalar. Filename of the **metadata** CSV
#'   (e.g., `"metadata.csv"`) located at `Data/<Network>/<metadataname>`.
#'   The file must contain, at minimum, the columns:
#'   - `IsActiveCharacteristicName` (character; expected value `"True"` for active)
#'   - `IsActiveSiteCode` (character; expected value `"True"` for active)
#'   - `DataName` (character; used to filter the data's `CharacteristicName`)
#'   - `SiteCode` (character; used to filter the data's `MonitoringLocationIdentifier`)
#' @param dataname Character scalar. Filename of the **data** CSV
#'   (e.g., `"data.csv"`) located at `Data/<Network>/<dataname>`. The file must
#'   contain, at minimum, the columns:
#'   - `CharacteristicName` (character)
#'   - `MonitoringLocationIdentifier` (character)
#'
#' @details
#' This function enforces two filters:
#'
#' 1. **Active characteristics**: Keeps rows in the metadata where
#'    `IsActiveCharacteristicName == "True"`.
#' 2. **Active sites**: Keeps rows in the metadata where
#'    `IsActiveSiteCode == "True"`.
#'
#' From the filtered metadata, it derives:
#' - `active_chars` as the unique values of `DataName`, used to filter
#'   the data column `CharacteristicName`.
#' - `active_sites` as the unique values of `SiteCode`, used to filter
#'   the data column `MonitoringLocationIdentifier`.
#'
#' The function writes out new CSVs with the suffix `"_activeonly"` added to
#' the base filenames (before the `.csv` extension) for both metadata and data:
#'
#' - Metadata output: `Data/<Network>/<metadataname_base>_activeonly.csv`
#' - Data output:     `Data/<Network>/<dataname_base>_activeonly.csv`
#'
#' If the active-only metadata file already exists, it is read and reused to
#' ensure the data filtering aligns exactly with the metadata previously deemed
#' active. The data active-only file is created if missing; otherwise, the
#' function simply returns its expected name.
#'
#' **Important column/value assumptions**
#' - `IsActiveCharacteristicName` and `IsActiveSiteCode` are compared to the
#'   **string** `"True"` (case-sensitive).
#' - `DataName` (metadata) corresponds to `CharacteristicName` (data).
#' - `SiteCode` (metadata) corresponds to `MonitoringLocationIdentifier` (data).
#'
#' @return
#' A named list with the two output filenames (not full paths):
#' \itemize{
#'   \item `mname_active`: the metadata active-only filename.
#'   \item `dname_active`: the data active-only filename.
#' }
#'
#' @section Side effects:
#' Reads and writes CSV files under `Data/<Network>/`. If active-only files
#' do not exist, they are created. Original base CSVs remain unchanged.
#'
#' @examples
#' \dontrun{
#' # Prepare active-only files for the NCRN network:
#' out_files <- filterActive(
#'   Network = "NCRN",
#'   metadataname = "metadata.csv",
#'   dataname = "water_quality.csv"
#' )
#'
#' # Filenames created or expected:
#' out_files$mname_active  # e.g., "metadata_activeonly.csv"
#' out_files$dname_active  # e.g., "water_quality_activeonly.csv"
#' }
#'
#' @seealso
#' \pkg{dplyr} for data manipulation verbs used internally.
#'
#' @author



library(dplyr)
filterActive <- function(Network, metadataname, dataname) {
  
  ### Filtering data to active Characteristics and Sites ####
  
  # NCRN maintains 'active' and 'inactive' characteristics and sites.
  
  # Through time, NCRN has monitoried different water quality characteristics.
  # This means that characteristics that are measured in 2025 may not have been measured in other years
  # and characteristics that were measured in 2006 may no longer be measured.
  # In Apr 2025, NCRN decided that including "all" characteristics was confusing
  # because so many picklist items were inactive.
  # To solve this problem, we filter the webapp's dataset to focus on what NCRN does right now.
  # For this reason, the lines below filter out inactive characteristics.
  # The full dataset (i.e., inactive and active) will be available in IRMA for
  # anyone interested in deprecated characteristics.
  
  # Through time, NCRN has monitored different sites; some have been retired and others added.
  # Since characteristics also change through time, sites usually have different recordsets (number of rows, unique CharacteristicNames, etc.) depending on which time they came from.
  # For example, Donaldson Run (NCRN_GWMP_DORU) has only two site visits from 2005 and is, therefore, difficult to reconcile with modern records because DORU returns zero rows for most queries.
  # The result is that the Shiny app is unstable if retired sites are left in the dataset.
  # Since the main reason NCRN retires sites is that they do not fit our protocol, we elected to filter-out retired sites instead of
  # building the app to accomodate the numerous edge cases caused by retired sites that are fundamentally apples-and-oranges to active sites.
  
  # make filenames
  appendix <- "_activeonly"
  
  mname_base <- base::strsplit(metadataname,'\\.csv')
  m_path_base <- file.path('Data',Network, metadataname)
  mname_active <- paste0(mname_base, appendix, ".csv")
  m_path_active <- file.path('Data',Network, mname_active)

  dname_base <- base::strsplit(dataname,'\\.csv')
  d_path_base <- file.path('Data',Network, dataname)
  dname_active <- paste0(dname_base, appendix, ".csv")
  d_path_active <- file.path('Data',Network, dname_active)
  
  # make files
  fnames <- list()
  
  if (file.exists(m_path_active)==F){
    # filter the metadata
    metadata_df <- read.csv(m_path_base)
    metadata_active <- metadata_df %>%
      dplyr::filter(IsActiveCharacteristicName == "True") %>%
      dplyr::filter(IsActiveSiteCode == "True") 
    write.csv(metadata_active, m_path_active, row.names = FALSE)
  } else {
    metadata_active <- read.csv(m_path_active) # this is a global variable 
  }
  fnames[['mname_active']] <- mname_active
  
  if (file.exists(d_path_active)==F){
    # filter the data
    active_chars <- metadata_active %>%
      dplyr::pull(DataName) %>% unique
    active_sites <- metadata_active %>%
      dplyr::pull(SiteCode) %>% unique
    
    filtered_data <- read.csv(d_path_base) %>%
      dplyr::filter(CharacteristicName %in% active_chars) %>%
      dplyr::filter(MonitoringLocationIdentifier %in% active_sites)
    write.csv(filtered_data, d_path_active, row.names = FALSE)
  }
  fnames[['dname_active']] <- dname_active
  
  return(fnames)
}